### ISSUE TITLE
Add dummy steps at end to hook on

### ISSUE THREAD

**Issue by dnd** [trailblazer/trailblazer-operation#2] opened 2017-01-06 18:36 UTC
Operation currently defines an `operation.new` step that can be hooked on to place some functionality before or after it. It would also be beneficial to think about including some steps at the end that maybe don't necessarily do anything, but would allow implementers to hook onto for generic functionality purposes.

Immediately three come to mind. `operation.end.success`, `operation.end.failure`, and then a final `operation.end`. I think that should cover parts of the operation lifecycle that an implementer can't current interact with.

**Comment by jairovm** [comment] 2017-11-01 01:29
I wanted to add a final step to all my Operation Classes that inherit from `ApplicationOperation` so basically this is how I made it worked.

```ruby
class ApplicationOperation < Trailblazer::Operation
  class << self
    def inherited(child)
      super

      TracePoint.trace(:end) do |tp|
        if child == tp.self
          child.add_final_step
          tp.disable
        end
      end
    end

  protected

    def add_final_step
      step -> (options) { ... }, name: 'final_step'
    end
  end
end
```

**Comment by apotonick** [comment] 2017-11-01 05:14
Hey, just letting you know, in 2.1, this becomes much easier. ETA 2 weeks

**Comment by panSarin** [comment] 2020-04-28 10:13
2.1 is published, the issue is from 2017 so i close it. Anyway thanks for the idea, and we are looking forward to furthering feedback!

**Closed by panSarin** 2020-04-28 10:13 UTC
